site_name: auto-spec-demo
site_url: https://twolversonreply.github.io/auto-spec-demo/
repo_url: https://github.com/TWolversonReply/auto-spec-demo

theme:
  name: material
  custom_dir: overrides
  font:
    text: Poppins
    code: Roboto Mono
  palette:
    scheme: valorem
    primary: custom
    accent: custom
  features:
    - navigation.sections
    - navigation.expand
    - toc.integrate

docs_dir: _build/docs

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences

plugins:
  - search

extra_css:
  - stylesheets/extra.css
